spring.application.name=CSVProcessor

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sample
spring.datasource.username=postgres
spring.datasource.password=kate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# File Upload Limits (prevent client memory overflow)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Caffeine Cache Spec (TTL and Maximum Size)
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=5000,expireAfterWrite=24h

# Change the Swagger UI browser path
springdoc.swagger-ui.path=/api-docs.html

# Change the raw JSON specification path
springdoc.api-docs.path=/api/v1/users/docs